# Generated by Django 4.2.23 on 2025-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtv_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
            ],
            options={
                'db_table': 'book_authors',
                'managed': False,
            },
        ),
    ]
